CREATE TABLE IF NOT EXISTS complaints (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'open',
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    sentiment TEXT NOT NULL DEFAULT 'neutral',
    category TEXT NOT NULL DEFAULT 'другое'
);


CREATE TABLE IF NOT EXISTS ip (
    ip TEXT PRIMARY KEY NOT NULL,
    number_requests INTEGER NOT NULL,
    block TEXT NOT NULL DEFAULT 'open'
);
